# Generated by Django 4.2.7 on 2023-11-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.CharField(choices=[('#Norway', '#Norway'), ('#Sweden', '#Sweden'), ('#Denmark', '#Denmark'), ('#Finland', '#Finland'), ('#Iceland', '#Iceland'), ('#Nordic', '#Nordic')], default='#Nordic', max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.TextField(blank=True, default='#Nordic'),
        ),
    ]
